"""initial database schema creation with core tables1

Revision ID: c86f3bc17a90
Revises:
Create Date: 2025-06-27 18:13:17.684975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c86f3bc17a90"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_tables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "academic_year_semester", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_tables_academic_year_semester"),
        "course_tables",
        ["academic_year_semester"],
        unique=False,
    )
    op.create_index(op.f("ix_course_tables_id"), "course_tables", ["id"], unique=False)
    op.create_table(
        "course_selections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_table_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_table_id"],
            ["course_tables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "course_table_id", "course_id", name="uix_course_table_course"
        ),
    )
    op.create_index(
        op.f("ix_course_selections_id"), "course_selections", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_course_selections_id"), table_name="course_selections")
    op.drop_table("course_selections")
    op.drop_index(op.f("ix_course_tables_id"), table_name="course_tables")
    op.drop_index(
        op.f("ix_course_tables_academic_year_semester"), table_name="course_tables"
    )
    op.drop_table("course_tables")
    # ### end Alembic commands ###
