services:
  api:
    image: ut-course-simulator:0.1.0
    container_name: ut-course-simulater
    depends_on:
      - db
    ports:
      - "8000:80"
    env_file:
      - .env
    restart: always

  db:
    image: postgres:17
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: